### ISSUE TITLE
API Setup

### ISSUE THREAD

**Issue by denvaar** [denvaar/show-n-tell#1]
## Background
I think it's agreed upon that this backend portion of our app will be implemented as an API. When I initialized this repository, I just used standard run-of-the-mill `mix phx.new` mix task. There's a better way for API's!

Check out `mix help phx.new` for more info.

## Requirements

Delete the generated code in this repo and instead use `mix phx.new --no-brunch --no-html` to generate a default phoenix app that is suitable for an API.

**Comment by alex-kovshovik** [comment]
This repo belongs to @denvaar, no one can self-assign issues and work on them, nor create/edit labels. Is there a way to add collaborators to this repo, so that we can have code reviews like in a Github organization?
