### ISSUE TITLE
Create schema for talks table

### ISSUE THREAD

**Issue by denvaar** [denvaar/show-n-tell#3]
## Background

As discussed in https://github.com/denvaar/show-n-tell/issues/2 during our meeting today, we need to create a `talks` database table. The purpose of this table is to hold the data related to the talks that people will share each week.

## Requirements

Please do #1 first, if it's not complete already.

Create a `talks` schema (or if you can think of a more appropriate name.) It needs the following fields to start with:

- `title` (string)
- `description` (text)
- `estimated_duration` (int)
- `date` (date)

## Hints

Check out the `phx.gen.schema` mix task.

**Comment by andrewjprice** [comment]
Would `presentations` schema be a more appropriate name?

**Comment by alex-kovshovik** [comment]
`presentations` is longer, `talks` is shorter and easier to type. In most cases we do talks, not really presentations. I'm fine either way tho.
