### ISSUE TITLE
Create Schema for users table

### ISSUE THREAD

**Issue by denvaar** [denvaar/show-n-tell#4]
## Background

As discussed in https://github.com/denvaar/show-n-tell/issues/2 during our meeting today, we need to create a `users` database table. The purpose of this table is to hold the data related to the users that will use this amazing piece of software.

## Requirements

Please do #1 first, if it's not complete already.

Create a `users` schema. It needs the following fields to start with:

- `name` (string)
- `encrypted_password` (text)

## Hints

- Check out the `phx.gen.schema` mix task.
- Don't store a plain text password

**Comment by alex-kovshovik** [comment]
To be discussed: is it OK to make this app "password-less"? Just use Github OAuth to authenticate users, simply store user accounts and their tokens I guess - anything that's needed for OAuth. I'd like to brush up on how OAuth really works for the case when there are 2 apps: a backend one and a separate front-end one.

Will describe the process in the next comment.

**Comment by alex-kovshovik** [comment]
I read the Github documentation on how their OAuth flow works. It is very standard, no problems:

1. Redirect user to https://github.com/login/oauth/authorize
2. Github redirects back with the `code`.
3. Make a POST call to https://github.com/login/oauth/access_token, pass in the `code` and `client_secret`.
4. Github responds with `access_token`.

The next few steps are to authenticate with the "Show & Tell API":

1. Send Github's `access_token` to "Show & Tell API".
2. Show & Tell API finds existing user or creates new user, assigns its own access_token (or even uses the one provided by Github, not sure about this one).
3. Client UI app receives the "Show & Tell API" token, stores it in the state, local storage.
4. Client UI uses the "Show & Tell API" token for all API calls.

The UML/sequence diagram of the whole process:

![github-oauth-sequence](https://user-images.githubusercontent.com/889219/38401590-da18bd5a-3913-11e8-97a3-8c6af5c36161.png)

I'm going to be working both on the prototype client UI app and the Show & Tell API - with the goal to build out the authentication part, for other Client UI apps to use.

**Comment by denvaar** [comment]
@alex-kovshovik Very awesome explanation and diagram! Thanks for putting the time and effort into this. So, with this in mind, what attributes does our user model need? Maybe `provider` and `uid`, which would hold `github` and `myemail@gmail.com`, for example? We won't need a password field it sounds like.

I think we should just create the users schema as part of this issue so that we can get started on the other issues that require it as a prerequisite. Then could you make a separate issue for the OAuth?

Does this sound good to you?

**Comment by alex-kovshovik** [comment]
@denvaar thank you, I think the following fields would be enough for users table:

- id
- first_name
- last_name
- email
- github_token
- audit fields: created_at, updated_at, created_by, updated_by

Basically, anything that our Client apps might want to display.

Also this is totally OK to do as part of a separate issue.
